### ISSUE TITLE
Turn a string to a channel?

### ISSUE THREAD

**Issue by JFulweber** [cavariux/twitchirc#5]
when I use onWhisper I just have it send a whisper back, like so:
`public void onWhisper(User user, String message){
        this.whisper(user, message);
        //this.sendMessage("BY GOD WE DID IT " + user + "SAID: " + message, channel);
}`
But there is no whisper sent back, so the event just doesn't work?

**Comment by lmariscal** [comment]
Well, the problem here is that the Whisper is a WIP, so I don't expect it to work right now. As stated in the README, nowadays I see is a more used function so I will try to make it happen for next update. Or if you know how to code this function the community would really appreciate it. Thanks :smile:
